[book]
title = "Nitid Documentation"
authors = ["Paolo Stefan"]
language = "en"
description = "Language spec, developer guide, and Rust API reference for the Nitid transpiler"

[build]
build-dir = "../../docs"
create-missing = false

[output.html]
no-section-label = true
git-repository-url = "https://github.com/paolostefan/nitid"
